language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --bootstrap=vendor/autoload.php tests/
  - vendor/bin/phpcs --standard=PSR2 src/ tests/
